definitions:
  steps:
  - step: &id004
      top_n: 25
      criterion: normalized_log_auc
      dock_files_to_use_from_previous_component:
        matching_spheres_file: false
        electrostatics_trim_phi_file: false
        electrostatics_phi_size_file: false
        vdw_file: false
        vdw_bump_map_file: false
        vdw_parameters_file: false
        ligand_desolvation_heavy_file: false
        ligand_desolvation_hydrogen_file: false
      parameters:
        custom_dock_executable: null
        dock_files_generation: &id002
          receptor_protonation:
            reduce_options: -HIS -FLIPs
          thin_spheres_elec:
            use: true
            molecular_surface_density: 1.0
            distance_to_surface: [1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2]
            penetration: 0.0
            distance_to_ligand: 2.0
          thin_spheres_desolv:
            use: true
            molecular_surface_density: 1.0
            distance_to_surface: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
            penetration: 0.0
            distance_to_ligand: 2.0
          ligand_desolvation:
            other_radius: 1.0
          covalent:
            use: false
            residue_num: 1
            residue_name: CYS
            residue_atoms: CA,CB,SG
        dock_files_modification:
          matching_spheres_perturbation:
            use: true
            num_samples_per_matching_spheres_file: 10
            max_deviation_angstroms: 0.4
        indock_file_generation: &id001
          ligand_atom_file: split_database_index
          output_file_prefix: test.
          match_method: 2
          distance_tolerance: 0.05
          match_goal: 1000
          distance_step: 0.05
          distance_maximum: 0.5
          timeout: 10.0
          nodes_maximum: 4
          nodes_minimum: 4
          bump_maximum:
          - 10.0
          - 100.0
          bump_rigid: 10.0
          mol2_score_maximum: 100.0
          chemical_matching: false
          case_sensitive: false
          atom_minimum: 4
          atom_maximum: 100
          number_save: 1
          number_write: 1
          flush_int: 100
          check_clashes: true
          do_premax: false
          do_clusters: false
          ligand_desolvation: volume
          ligand_desolv_scale: 1.0
          electrostatic_scale: 1.0
          vdw_scale: 1.0
          internal_scale: 0.0
          per_atom_scores: false
          dockovalent: false
          bond_len: 1.8
          bond_ang1: 109.5
          bond_ang2: 109.5
          len_range: 0.0
          len_step: 0.1
          ang1_range: 10.0
          ang2_range: 10.0
          ang1_step: 2.5
          ang2_step: 2.5
          minimize: true
          sim_itmax: 500
          sim_trnstep: 0.2
          sim_rotstep: 5.0
          sim_need_to_restart: 1.0
          sim_cnvrge: 0.1
          min_cut: 1.0e15
          iseed: 777
          flexible_receptor: false
          total_receptors: 1
          rec_number: 1
          rec_group: 1
          rec_group_option: 1
          check_strain: true
          total_strain: 8
          max_strain: 3
  - step: &id005
      top_n: 25
      criterion: normalized_log_auc
      dock_files_to_use_from_previous_component:
        matching_spheres_file: false
        electrostatics_trim_phi_file: false
        electrostatics_phi_size_file: false
        vdw_file: false
        vdw_bump_map_file: false
        vdw_parameters_file: false
        ligand_desolvation_heavy_file: false
        ligand_desolvation_hydrogen_file: false
      parameters:
        custom_dock_executable: null
        dock_files_generation:
          receptor_protonation:
            reduce_options: -HIS -FLIPs
          thin_spheres_elec:
            use: true
            molecular_surface_density: 1.0
            distance_to_surface:
              reference_value: ^
              arguments:
              - -0.05
              - -0.04
              - -0.03
              - -0.02
              - -0.01
              - 0.0
              - 0.01
              - 0.02
              - 0.03
              - 0.04
              - 0.05
              operator: +
            penetration: 0.0
            distance_to_ligand: 2.0
          thin_spheres_desolv:
            use: true
            molecular_surface_density: 1.0
            distance_to_surface:
              reference_value: ^
              arguments:
              - -0.05
              - -0.04
              - -0.03
              - -0.02
              - -0.01
              - 0.0
              - 0.01
              - 0.02
              - 0.03
              - 0.04
              - 0.05
              operator: +
            penetration: 0.0
            distance_to_ligand: 2.0
          ligand_desolvation:
            other_radius: 1.0
          covalent:
            use: false
            residue_num: 1
            residue_name: CYS
            residue_atoms: CA,CB,SG
        dock_files_modification:
          matching_spheres_perturbation:
            use: true
            num_samples_per_matching_spheres_file: 10
            max_deviation_angstroms: 0.4
        indock_file_generation: *id001
  - step: &id003
      top_n: 20
      criterion: normalized_log_auc
      dock_files_to_use_from_previous_component:
        matching_spheres_file: true
        electrostatics_trim_phi_file: true
        electrostatics_phi_size_file: true
        vdw_file: true
        vdw_bump_map_file: true
        vdw_parameters_file: true
        ligand_desolvation_heavy_file: true
        ligand_desolvation_hydrogen_file: true
      parameters:
        custom_dock_executable: null
        dock_files_generation: *id002
        dock_files_modification:
          matching_spheres_perturbation:
            use: true
            num_samples_per_matching_spheres_file: 50
            max_deviation_angstroms: 0.2
        indock_file_generation: *id001
  sequences:
  - sequence: &id006
      top_n: 20
      inter_iteration_top_n: 20
      criterion: normalized_log_auc
      inter_iteration_criterion: normalized_log_auc
      num_iterations: 20
      max_iterations_with_no_improvement: 20
      components:
      - step: *id003
pipeline:
  top_n: 5
  criterion: normalized_log_auc
  components:
  - step: *id004
  - step: *id005
  - sequence: *id006
