definitions:
  steps:
    list(include('step_list_item'), min=1)
  sequences:
    list(include('sequence_list_item'), min=0)
pipeline:
  top_n: num()
  criterion: str()
  components: list(include('step', required=False), include('sequence', required=False), min=1)

---

numerically_operative_multivalued_parameter:
  reference_value: any(regex('^[\^]$'), num())
  arguments: list(num())
  operator: regex('^[+*]$')

step:
  top_n: num()
  criterion: str()
  dock_files_to_copy_from_previous_step:
    matching_spheres_file: bool()
    electrostatics_trim_phi_file: bool()
    electrostatics_phi_size_file: num()
    vdw_file: bool()
    vdw_bump_map_file: bool()
    vdw_parameters_file: bool()
    ligand_desolvation_heavy_file: bool()
    ligand_desolvation_hydrogen_file: bool()
  parameters:
    custom_dock_executable: any(null(), str(), list(null(required=False), str(required=False)), min=1)
    dock_files_generation:
      receptor_protonation:
        reduce_options: any(str(), list(str()), include('numerically_operative_multivalued_parameter'))
      thin_spheres_elec:
        use: any(bool(), list(bool()))
        molecular_surface_density: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
        distance_to_surface: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
        penetration: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
        distance_to_ligand: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      thin_spheres_desolv:
        use: any(bool(), list(bool()))
        molecular_surface_density: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
        distance_to_surface: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
        penetration: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
        distance_to_ligand: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      ligand_desolvation:
        other_radius: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      covalent:
        use: any(bool(), list(bool()))
        residue_num: any(int(), list(int()))
        residue_name: any(str(), list(str()))
        residue_atoms: any(str(), list(str()))
    dock_files_modification:
      matching_spheres_perturbation:
        use: bool()
        num_samples_per_matching_spheres_file: num()
        max_deviation_angstroms: num()
    indock:
      ligand_atom_file: any(str(), list(str()))
      output_file_prefix: any(str(), list(str()))
      match_method: any(int(), list(int()))
      distance_tolerance: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      match_goal: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))
      distance_step: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      distance_maximum: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      timeout: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      nodes_maximum: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))
      nodes_minimum: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))
      bump_maximum: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      bump_rigid: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      mol2_score_maximum: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      chemical_matching: any(bool(), list(bool()))
      case_sensitive: any(bool(), list(bool()))
      atom_minimum: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))
      atom_maximum: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))
      number_save: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))
      number_write: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))
      flush_int: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))
      check_clashes: any(bool(), list(bool()))
      do_premax: any(bool(), list(bool()))
      do_clusters: any(bool(), list(bool()))
      ligand_desolvation: any(str(), list(str()))
      ligand_desolv_scale: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      electrostatic_scale: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      vdw_scale: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      internal_scale: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      per_atom_scores: any(bool(), list(bool()))
      dockovalent: any(bool(), list(bool()))
      bond_len: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      bond_ang1: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      bond_ang2: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      len_range: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      len_step: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      ang1_range: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      ang2_range: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      ang1_step: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      ang2_step: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      minimize: any(bool(), list(bool()))
      sim_itmax: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))
      sim_trnstep: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      sim_rotstep: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      sim_need_to_restart: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      sim_cnvrge: any(num(), list(num()), include('numerically_operative_multivalued_parameter'))
      min_cut: any(str(), list(str()))
      iseed: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))
      flexible_receptor: any(bool(), list(bool()))
      total_receptors: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))
      rec_number: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))
      rec_group: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))
      rec_group_option: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))
      check_strain: any(bool(), list(bool()))
      total_strain: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))
      max_strain: any(int(), list(int()), include('numerically_operative_multivalued_parameter'))

sequence:
  top_n: num()
  criterion: str()
  num_repetitions: int(min=0)
  max_iterations_with_no_improvement: int(min=0)
  components: list(include('step_list_item'), include('sequence_list_item'), min=1)

step_list_item:
  step: include('step')

sequence_list_item:
  sequence: include('sequence')
