definitions:
  steps:
    list(include('step_list_item'), min=1)
  sequences:
    list(include('sequence_list_item'), min=1)
pipeline:
  top_n: num()
  criterion: str()
  components: list(include('step_list_item', required=False), include('sequence_list_item', required=False), min=1)

---

numerically_operative_multivalued_parameter:
  reference_value: any(regex('^[\^]$'), num())
  arguments: list(num())
  operator: regex('^[+*]$')

step:
  top_n: num()
  criterion: str()
  dock_files_to_use_from_previous_component:
    matching_spheres_file: bool()
    electrostatics_trim_phi_file: bool()
    electrostatics_phi_size_file: bool()
    vdw_file: bool()
    vdw_bump_map_file: bool()
    vdw_parameters_file: bool()
    ligand_desolvation_heavy_file: bool()
    ligand_desolvation_hydrogen_file: bool()
  parameters:
    dock_executable_path: any(regex('^[\^]$'), null(), str(), list(null(required=False), str(required=False)), min=1)
    dock_files_generation:
      receptor_protonation:
        reduce_options: any(regex('^[\^]$'), str(), list(str()), include('numerically_operative_multivalued_parameter'))
      thin_spheres_elec:
        use: any(regex('^[\^]$'), bool(), list(bool()))
        molecular_surface_density: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
        distance_to_surface: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
        penetration: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
        distance_to_ligand: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      thin_spheres_desolv:
        use: any(regex('^[\^]$'), bool(), list(bool()))
        molecular_surface_density: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
        distance_to_surface: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
        penetration: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
        distance_to_ligand: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      ligand_desolvation:
        other_radius: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      covalent:
        use: any(regex('^[\^]$'), bool(), list(bool()))
        residue_num: any(regex('^[\^]$'), int(), list(int()))
        residue_name: any(regex('^[\^]$'), str(), list(str()))
        residue_atoms: any(regex('^[\^]$'), str(), list(str()))
    dock_files_modification:
      matching_spheres_perturbation:
        use: any(regex('^[\^]$'), bool(), list(bool()))
        num_samples_per_matching_spheres_file: num()
        max_deviation_angstroms: any(regex('^[\^]$'), num())
    indock_file_generation:
      ligand_atom_file: any(regex('^[\^]$'), str(), list(str()))
      output_file_prefix: any(regex('^[\^]$'), str(), list(str()))
      match_method: any(regex('^[\^]$'), int(), list(int()))
      distance_tolerance: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      match_goal: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))
      distance_step: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      distance_maximum: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      timeout: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      nodes_maximum: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))
      nodes_minimum: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))
      bump_maximum: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      bump_rigid: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      mol2_score_maximum: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      chemical_matching: any(regex('^[\^]$'), bool(), list(bool()))
      case_sensitive: any(regex('^[\^]$'), bool(), list(bool()))
      atom_minimum: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))
      atom_maximum: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))
      number_save: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))
      number_write: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))
      flush_int: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))
      check_clashes: any(regex('^[\^]$'), bool(), list(bool()))
      do_premax: any(regex('^[\^]$'), bool(), list(bool()))
      do_clusters: any(regex('^[\^]$'), bool(), list(bool()))
      ligand_desolvation: any(regex('^[\^]$'), str(), list(str()))
      ligand_desolv_scale: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      electrostatic_scale: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      vdw_scale: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      internal_scale: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      per_atom_scores: any(regex('^[\^]$'), bool(), list(bool()))
      dockovalent: any(regex('^[\^]$'), bool(), list(bool()))
      bond_len: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      bond_ang1: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      bond_ang2: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      len_range: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      len_step: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      ang1_range: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      ang2_range: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      ang1_step: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      ang2_step: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      minimize: any(regex('^[\^]$'), bool(), list(bool()))
      sim_itmax: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))
      sim_trnstep: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      sim_rotstep: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      sim_need_to_restart: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      sim_cnvrge: any(regex('^[\^]$'), num(), list(num()), include('numerically_operative_multivalued_parameter'))
      min_cut: any(regex('^[\^]$'), str(), list(str()))
      iseed: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))
      flexible_receptor: any(regex('^[\^]$'), bool(), list(bool()))
      total_receptors: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))
      rec_number: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))
      rec_group: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))
      rec_group_option: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))
      check_strain: any(regex('^[\^]$'), bool(), list(bool()))
      total_strain: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))
      max_strain: any(regex('^[\^]$'), int(), list(int()), include('numerically_operative_multivalued_parameter'))

sequence:
  top_n: num()
  inter_iteration_top_n: num()
  criterion: str()
  inter_iteration_criterion: str()
  num_repetitions: int(min=0)
  max_iterations_with_no_improvement: int(min=0)
  components: list(include('step_list_item'), include('sequence_list_item'), min=1)

step_list_item:
  step: include('step')

sequence_list_item:
  sequence: include('sequence')
