receptor_protonation:
  reduce_options: any(str(), list(str()))

thin_spheres_elec:
  use: any(bool(), list(bool()))
  molecular_surface_density: any(num(), list(num()))
  distance_to_surface: any(num(), list(num()))
  penetration: any(num(), list(num()))
  distance_to_ligand: any(num(), list(num()))

thin_spheres_desolv:
  use: any(bool(), list(bool()))
  molecular_surface_density: any(num(), list(num()))
  distance_to_surface: any(num(), list(num()))
  penetration: any(num(), list(num()))
  distance_to_ligand: any(num(), list(num()))

ligand_desolvation:
  other_radius: any(num(), list(num()))

covalent:
  use: any(bool(), list(bool()))
  residue_num: any(int(), list(int()))
  residue_name: any(str(), list(str()))
  residue_atoms: any(str(), list(str()))

indock:
  ligand_atom_file: any(str(), list(str()))
  output_file_prefix: any(str(), list(str()))
  match_method: any(int(), list(int()))
  distance_tolerance: any(num(), list(num()))
  match_goal: any(int(), list(int()))
  distance_step: any(num(), list(num()))
  distance_maximum: any(num(), list(num()))
  timeout: any(num(), list(num()))
  nodes_maximum: any(int(), list(int()))
  nodes_minimum: any(int(), list(int()))
  bump_maximum: any(num(), list(num()))
  bump_rigid: any(num(), list(num()))
  mol2_score_maximum: any(num(), list(num()))
  chemical_matching: any(bool(), list(bool()))
  case_sensitive: any(bool(), list(bool()))
  atom_minimum: any(int(), list(int()))
  atom_maximum: any(int(), list(int()))
  number_save: any(int(), list(int()))
  number_write: any(int(), list(int()))
  flush_int: any(int(), list(int()))
  check_clashes: any(bool(), list(bool()))
  do_premax: any(bool(), list(bool()))
  do_clusters: any(bool(), list(bool()))
  ligand_desolvation: any(str(), list(str()))
  ligand_desolv_scale: any(num(), list(num()))
  electrostatic_scale: any(num(), list(num()))
  vdw_scale: any(num(), list(num()))
  internal_scale: any(num(), list(num()))
  per_atom_scores: any(bool(), list(bool()))
  dockovalent: any(bool(), list(bool()))
  bond_len: any(num(), list(num()))
  bond_ang1: any(num(), list(num()))
  bond_ang2: any(num(), list(num()))
  len_range: any(num(), list(num()))
  len_step: any(num(), list(num()))
  ang1_range: any(num(), list(num()))
  ang2_range: any(num(), list(num()))
  ang1_step: any(num(), list(num()))
  ang2_step: any(num(), list(num()))
  minimize: any(bool(), list(bool()))
  sim_itmax: any(int(), list(int()))
  sim_trnstep: any(num(), list(num()))
  sim_rotstep: any(num(), list(num()))
  sim_need_to_restart: any(num(), list(num()))
  sim_cnvrge: any(num(), list(num()))
  min_cut: any(str(), list(str()))
  iseed: any(int(), list(int()))
  flexible_receptor: any(bool(), list(bool()))
  total_receptors: any(int(), list(int()))
  rec_number: any(int(), list(int()))
  rec_group: any(int(), list(int()))
  rec_group_option: any(int(), list(int()))